version: '2'

services:
  web:
    build: .
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/react-starter-app/src
      - /var/www/react-starter-app/src/node_modules
